//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace med
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocInitializations
    {
        public int id { get; set; }
        public int FamilyDoctorID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual FamilyDoctors FamilyDoctors { get; set; }
    }
}
