//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace med
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedecineEntities : DbContext
    {
        public MedecineEntities()
            : base("name=MedecineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddDelete> AddDelete { get; set; }
        public virtual DbSet<Analyzes> Analyzes { get; set; }
        public virtual DbSet<ArchivePatients> ArchivePatients { get; set; }
        public virtual DbSet<ArchiveRecover> ArchiveRecover { get; set; }
        public virtual DbSet<ArchiveTestResults> ArchiveTestResults { get; set; }
        public virtual DbSet<DocInitializations> DocInitializations { get; set; }
        public virtual DbSet<FamilyDoctors> FamilyDoctors { get; set; }
        public virtual DbSet<HospitalsData> HospitalsData { get; set; }
        public virtual DbSet<Illness> Illness { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<Procedures> Procedures { get; set; }
        public virtual DbSet<Recover> Recover { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TestResults> TestResults { get; set; }
    }
}
