//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace med
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResults
    {
        public int id { get; set; }
        public System.DateTime Date { get; set; }
        public int PatientId { get; set; }
        public int AnalyzeID { get; set; }
        public string FileName { get; set; }
        public string Title { get; set; }
        public byte[] ResultData { get; set; }
    
        public virtual Analyzes Analyzes { get; set; }
    }
}
